# Generated by Django 3.1.5 on 2021-02-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chat',
            field=models.TextField(default='home'),
            preserve_default=False,
        ),
    ]
