# Generated by Django 3.1.5 on 2021-02-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
