# Generated by Django 3.1.5 on 2021-02-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20210204_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
