# Generated by Django 3.1.5 on 2021-02-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20210223_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'State List'},
        ),
        migrations.AlterModelTable(
            name='exercise',
            table='state',
        ),
    ]
