# Generated by Django 3.1.5 on 2021-02-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_auto_20210223_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={},
        ),
        migrations.AlterModelTable(
            name='exercise',
            table=None,
        ),
    ]
